AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: "Count macro A simple iterator for creating multipledentical resources\n"
Resources:
  Macro:
    Type: AWS::CloudFormation::Macro
    Properties:
      Name: Count
      FunctionName:
        Fn::GetAtt:
        - CountMacroFunction
        - Arn
  CountMacroFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://count-cloudformation-macro-5675/c6bcffd28b44b4f43ba5a0127047489c
      Handler: index.handler
      Runtime: python3.7
      Timeout: 5
